### ISSUE TITLE
Adding custom operators breaks R8/Proguard

### ISSUE THREAD

**Issue by sadellie** [ezylang/EvalEx#338]
### My setup
I have added some custom operators as follows:
```kotlin
@PrefixOperator(precedence = OPERATOR_PRECEDENCE_POWER)
class SqrtOperatorWithoutBracket : AbstractOperator() {
    override fun evaluate(
        expression: Expression?, operatorToken: Token?, vararg operands: EvaluationValue
    ): EvaluationValue {
        // Some valid code here
        ...
    }
}
```

My _**proguard-rules.pro**_ file looks like this:
```
-keepclassmembers class ** {
    @com.squareup.moshi.FromJson *;
    @com.squareup.moshi.ToJson *;
}
```

### The problem

When building APK without any code shrinking, everything is fine and app can be installed/launched as expected.

When building APK with code shrinking, app builds with following output:
```
> Task :app:minifyFdroidReleaseWithR8
AGPBI: {"kind":"warning","text":"Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in C:\\...\\missing_rules.txt.\n","sources":[{}]}
AGPBI: {"kind":"warning","text":"Missing class lombok.Generated (referenced from: boolean com.ezylang.evalex.config.ExpressionConfiguration$ExpressionConfigurationBuilder.allowOverwriteConstants$set and 107 other contexts)","sources":[{}],"tool":"R8"}
Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in C:\...\missing_rules.txt.


Missing class lombok.Generated (referenced from: boolean com.ezylang.evalex.config.ExpressionConfiguration$ExpressionConfigurationBuilder.allowOverwriteConstants$set and 107 other contexts)
```
App can be installed, but crashes on launch.

### Things I've already tried
Adding this lines to `keepclassmembers` didn't help:
```
@com.ezylang.evalex.config.ExpressionConfiguration *;
@lombok.Generated *;
```

Adding Lombok as plugin didn't work:
```kotlin
id("io.freefair.lombok") version "6.6"
```

### Question
How do I make code shrinking work properly?

**Comment by uklimaschewski** [comment]
Without knowing much about Proguard, I think this link might give you some help: https://stackoverflow.com/questions/25314202/proguard-build-failure-with-lombok-annotation-library

Lombok is only used during compile time in EvalEx, so it is added as a provided dependency to Maven.
In Gradle, I think you should add it as a compileOnly dependency:

`dependencies {
	compileOnly "org.projectlombok:lombok:1.18.24"
}`

Here is some more information: https://projectlombok.org/setup/android

**Comment by sadellie** [comment]
1. Looks like Proguard is broken even without custom operators. Just using EvalEx is causing this issue.
2. Your suggestion didn't help

I managed to get some logs from device, first few lines are kinda usable, but the rest is is not important (after obfuscation).

```
2022-12-06 22:43:25.075 26056-26056 AndroidRuntime          pid-26056                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.sadellie.unitto, PID: 26056
                                                                                                    java.lang.AssertionError: annotation container = @k3.e()annotation element class = interface k3.c; missing value() method
                                                                                                    	at libcore.reflect.AnnotatedElements.insertAnnotationValues(AnnotatedElements.java:98)
                                                                                                    	at libcore.reflect.AnnotatedElements.getDirectOrIndirectAnnotationsByType(AnnotatedElements.java:63)
                                                                                                    	at java.lang.reflect.AnnotatedElement.getAnnotationsByType(AnnotatedElement.java:327)
                                                                                                    	at java.lang.Class.getAnnotationsByType(Class.java:2538)
                                                                                                    	at k3.a.<init>(Unknown Source:16)
```

`missing value() method` Is probably related to Lombok's `@Value` annotation. I`ll try to find a workaround.

P.S. Kinda strange that I am first to face this issue. Is no one minifying their app size or my setup is wrong?

**Comment by uklimaschewski** [comment]
For the record, from #340:

You should exclude EvalEx (package com.ezylag.evalex) from ProGuard, as this is a open source library anyways.
It makes absolutely no sense to obfuscate open source libraries. Anybody who wants to see the original source code, can do this here.

Without testing it, this should work if you add it to your proguard.config:
```
-keep class com.ezylag.evalex.** { *; }
-dontwarn com.ezylag.evalex.**
```
