### ISSUE TITLE
NoSuchElementException not being caught

### ISSUE THREAD

**Issue by agronick** [ezylang/EvalEx#402]
I got this bug report today. I am catching `BaseException`. I think this should probably be caught in the library and recast to something that extends `BaseException`. I don't know what formula the user used to cause it.

```
java.util.NoSuchElementException
at java.util.ArrayDeque.removeFirst(ArrayDeque.java:370)
at java.util.ArrayDeque.pop(ArrayDeque.java:601)
at com.ezylang.evalex.parser.ShuntingYardConverter.processBraceClose(Unknown Source:49)
at com.ezylang.evalex.parser.ShuntingYardConverter.toAbstractSyntaxTree(Unknown Source:75)
at com.ezylang.evalex.Expression.getAbstractSyntaxTree(Unknown Source:26)
at com.ezylang.evalex.Expression.evaluate(Unknown Source:0)
```

**Comment by agronick** [comment]
Here is another one 
```java.lang.NumberFormatException: Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
at java.math.BigDecimal.<init>(BigDecimal.java:595)
at java.math.BigDecimal.<init>(BigDecimal.java:480)
at java.math.BigDecimal.<init>(BigDecimal.java:909)
at java.math.BigDecimal.valueOf(BigDecimal.java:1377)
at com.ezylang.evalex.data.EvaluationValue.convertToBigDecimal(Unknown Source:17)
at com.ezylang.evalex.data.EvaluationValue.<init>(SourceFile:2)
at com.ezylang.evalex.Expression.with(Unknown Source:44)```

**Comment by uklimaschewski** [comment]
Please provide a complete example, including the causing expression.
Else I don't know if this should be an exception that has to be caught, or something that can already be handled while parsing the expression, giving a parsing error.
