### ISSUE TITLE
Java exception generated when trying to calculate expressions (it worked before with the original EvalEX library in the previous GitHub)

### ISSUE THREAD

**Issue by Megabyte94** [ezylang/EvalEx#464]
Caused by androidx.datastore.preferences.protobuf.t0: Operator annotation for 'E1.a' not found
       at com.ezylang.evalex.operators.OperatorAnnotationNotFoundException.<init>(OperatorAnnotationNotFoundException.java:118)
       at com.ezylang.evalex.operators.AbstractOperator.<init>(AbstractOperator.java:118)
       at com.ezylang.evalex.config.ExpressionConfiguration.$default$operatorDictionary(ExpressionConfiguration.java:28)
       at com.ezylang.evalex.config.ExpressionConfiguration$ExpressionConfigurationBuilder.build(ExpressionConfiguration.java:28)
       at com.Kenneth_Technologies.SigMath.fragments.CalculatorFragment.<clinit>(CalculatorFragment.java:28)
       at com.Kenneth_Technologies.SigMath.activities.MainActivity.loadCalculatorFragment(MainActivity.java:18)
       at com.Kenneth_Technologies.SigMath.activities.MainActivity.onCreate(MainActivity.java:575)
       at android.app.Activity.performCreate(Activity.java:8944)
       at android.app.Activity.performCreate(Activity.java:8913)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by uklimaschewski** [comment]
Hi,

can you give some more information on what you are doing?
What is the expression string and how did you configure the expression?

Some test code that can reproduce the exception would be nice.

**Comment by uklimaschewski** [comment]
Closing this issue due to inactivity.
